[package]
name = "helipad"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.6", default-features = false, features = ["async-await"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.12.0", features = ["full"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-aux = "3.0.1"
route-recognizer = "0.2"
bytes = "0.5"
async-trait = "0.1"
url = "2.2.1"
rusqlite = "0.26.1"
drop-root = "0.1.1"
percent-encoding = "2.1.0"
prost = "0.6.1"
websocket = "0.24.0"
dbif = { path = 'dbif'}
lnd-rs = { path = "lnd-rs" }
voca_rs = "1.14.0"